spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./h2db/sample
      driver-class-name: org.h2.Driver
      username: sa
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: hikari
  h2:
    console:
      path: /h2console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

